wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1646924299
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      - 16
      - 24
      - 29
      4: 3.7.4
      5: 0.12.11
      8:
      - 5
